#!/usr/bin/python3

import argparse
import sys
from cli_commands.list_command import ListCommand

def main():
    main_parser = argparse.ArgumentParser()
    subparsers = main_parser.add_subparsers(dest='cmd')

    list_command = ListCommand()
    list_command.parse_arguments(subparsers)
       
    if len(sys.argv) == 1:
        main_parser.print_help()
    else:
        args = main_parser.parse_args()
        args.func(args)

if __name__ == "__main__":
    #execute only if run as a script
    main()
